oxfordcontrol/Clarabel.rs

.github/workflows/pypi.yaml

These are useful for running Clarabel in arm-based servers in the cloud, or when inside Docker environments in macs with arm based chips.

Release binaries for arm64 linux

---

Cargo.toml
src/algebra/dense/blas.rs

The cargo for blas-src and lapack-src now provides a feature "r" for using the blas and lapack that come with R. However, the R blas/lapack only provides double precision routines. So this also includes patches to conditionally compile only double precision routines when feature "sdp-r" is used.  This addresses [issue](https://github.com/oxfordcontrol/clarabel-r/issues/4) raised by @goulart-paul. 
PS. I have tested this with rust version 1.69.0.

Add BLAS/LAPACK feature for R, conditionally use f32 implementations

---

src/solver/implementations/default/kktsystem.rs

Fixes an error in variable initialization for problems with purely linear objectives.
Tracking change for https://github.com/oxfordcontrol/Clarabel.jl/pull/134

fixes LP style initialization

---

src/algebra/csc/core.rs

Addresses https://github.com/oxfordcontrol/Clarabel.rs/issues/38

Provides utility for making allocated cscmatrix from an adjoint.

---

src/julia/ClarabelRs/src/types.jl
src/julia/types.rs
src/solver/implementations/default/solution.rs
tests/basic_lp.rs
tests/basic_qp.rs
tests/basic_socp.rs

Report dual objective values

---

src/algebra/csc/core.rs
src/algebra/csc/utils.rs
src/algebra/error_types.rs
src/algebra/math_traits.rs
src/algebra/vecmath.rs
src/solver/core/kktsolvers/direct/quasidef/directldlkktsolver.rs
src/solver/core/kktsolvers/mod.rs
src/solver/core/solver.rs
src/solver/core/traits.rs
src/solver/implementations/default/data_updating.rs
src/solver/implementations/default/info.rs
src/solver/implementations/default/kktsystem.rs
src/solver/implementations/default/mod.rs
src/solver/implementations/default/problemdata.rs
tests/data_updating.rs

WIP : adds methods for updating P / q / A / b components of problem data in a solver, provided that the original sparsity patterns have not changed.
Addresses #59.   Not yet complete because it still requires C/C++/Python wrappers.

Add methods for problem data updates

---

.github/workflows/pypi.yaml
.github/workflows/testpypi.yaml

Reverts oxfordcontrol/Clarabel.rs#86.   See also here: https://github.com/actions/upload-artifact/issues/472

Revert "Bump actions/download-artifact from 3 to 4"

---

src/algebra/csc/mod.rs
src/algebra/dense/blaslike_traits.rs
src/algebra/dense/block_concatenate.rs
src/algebra/dense/mod.rs
src/algebra/densesym3x3/mod.rs
src/algebra/matrix_traits.rs
src/algebra/mod.rs
src/qdldl/test.rs
src/solver/core/cones/compositecone.rs
src/solver/core/cones/expcone.rs
src/solver/core/cones/genpowcone.rs
src/solver/core/cones/nonnegativecone.rs
src/solver/core/cones/powcone.rs
src/solver/core/cones/psdtrianglecone.rs
src/solver/core/cones/socone.rs
src/solver/core/cones/supportedcone.rs
src/solver/core/cones/symmetric_common.rs
src/solver/core/cones/zerocone.rs
src/solver/core/kktsolvers/direct/quasidef/kkt_assembly.rs
src/solver/core/kktsolvers/direct/quasidef/mod.rs
src/solver/core/solver.rs
src/solver/implementations/default/info_print.rs
src/solver/implementations/default/mod.rs

Resolves new linter warnings in v1.75, most of which relate to redundant imports or unused functions.   Fix for #83.

Resolve lint warnings for rustc >=v1.75

---

Cargo.toml

Fixes an occasional issue with MKL compilation by specifying that we want to use the LP64 format, i.e. 32 bit integer types.

force mkl LP64 format (32 bit ints)

---

Cargo.toml
src/solver/core/kktsolvers/direct/quasidef/datamaps.rs
src/solver/core/kktsolvers/direct/quasidef/ldlsolvers/faer_ldl.rs

Increase version of faer to 0.20.   This makes rustc v1.81 the MSRV when compiling with `faer-sparse`.
Note that v1.83 actually seems to be required since the `pulp` dependency for `faer` implicitly requires v1.83.

update faer version to v.0.20

---

.github/workflows/pypi.yaml
.github/workflows/testpypi.yaml
Cargo.toml
pyproject.toml
src/algebra/floats.rs
src/python/cones_py.rs
src/python/cscmatrix_py.rs
src/python/impl_default_py.rs
src/python/io.rs
src/python/module_py.rs
src/python/pyblas/mod.rs
src/solver/core/kktsolvers/direct/quasidef/directldlkktsolver.rs
src/solver/implementations/default/kktsystem.rs

Produce python abi3 outputs with MSV python 3.9.   This remains compatible with cvxpy, which also requires >= 3.9.
Updating now since some CI builds have begun failing on `ubuntu-latest` with python 3.7.
Internal updates for compatibility with pyo3 v0.23 to support python 3.13.
Fixes #146

Python 3.7/3.8 EOL update

---

src/algebra/csc/utils.rs
src/solver/core/kktsolvers/direct/quasidef/kkt_assembly.rs

Modifies KKT assembly internals so that the function that counts diagonal entries works for either triu/tril form, but the form of the matrix must be explicitly passed.
This function is currently only ever applied to the user-supplied `P` matrix, so should only ever count diagonal terms on a triu matrix.    Including this modification anyway since it makes assumptions more explicit, and might also prevent a bug in some future version that allows full matrices to be passed.   Also added some unit tests.
Related : #143, which this replaces.

enable CSC diagonal counting for triu/tril

---

Cargo.toml
src/timers/timers.rs
tests/basic_qp.rs

wasm as platform dependency

---

src/solver/core/cones/socone.rs

Fixes error condition identified in example of https://github.com/cvxpy/cvxpy/issues/2610
Port of fix in https://github.com/oxfordcontrol/Clarabel.jl/pull/180

fix socp line search failure case

---

src/solver/implementations/default/info.rs
src/solver/implementations/default/settings.rs
src/solver/implementations/default/variables.rs

Port of the fix in https://github.com/oxfordcontrol/Clarabel.jl/pull/179
This appears to fix #120.

Port of julia #179

---

src/algebra/csc/core.rs
src/python/cscmatrix_py.rs

Utilities for converting to CSC canonicalization / deduplication.  

---

src/algebra/csc/core.rs
src/solver/implementations/default/settings.rs

Compilation currently fails without the "serde" feature enabled because the use of `#[serde(...)]` isn't conditioned on the feature being enabled. This PR uses `cfg_attr` to do so similar to the `Serialize` and `Deserialize` derives.

Fix compilation failure without "serde" feature

---

Cargo.toml
build.rs
src/algebra/dense/blas/traits.rs
src/python/mod.rs
src/python/module_py.rs

This allows the solver to be compiled for python *without* using blas/lapack functions from scipy.   Specifying one of the supported blas/lapack features (e.g. `sdp-mkl`, `sdp-accelerate') will now use those instead, following the behaviour of non-python builds.
If the `python` feature is specified without naming a blas distribution, then the previous behaviour of acquiring blas/lapack pointers from scipy is maintained.   This is the preferred method in particular for distribution on pypi.
Note that the python interface should still be built via `maturin`.    
For the standard build with the clarabel using scipy blas / lapack:
```maturin develop --release```
To build the python interface using a local blas/lapack distribution (e.g. mkl):
``` maturin develop --release --features …
```

Allow python to build with non-scipy blas and lapack

---

Cargo.toml
build.rs
src/algebra/dense/blas/traits.rs
src/algebra/floats.rs
src/julia/ClarabelRs/src/ClarabelRs.jl
src/julia/ClarabelRs/test/test_problem_depot.jl
src/python/impl_default_py.rs
src/python/io.rs
src/solver/core/kktsolvers/direct/quasidef/ldlsolvers/faer_ldl.rs
src/solver/implementations/default/info_print.rs
src/solver/implementations/default/settings.rs
src/stdio/mod.rs

Fixes #154.    
Adds build information function.
Adds configurable thread count to settings.

update to faer v0.21

---

examples/python/example_qp_update.py
src/python/cscmatrix_py.rs
src/python/impl_default_py.rs
src/solver/implementations/default/data_updating.rs
tests/data_updating.rs

Implements data updating functions for python wrapper.

python data updates.  Fixes #75

---

python/clarabel/tests/test_data_update.py
src/python/impl_default_py.rs
src/solver/implementations/default/data_updating.rs
src/solver/implementations/default/problemdata.rs
tests/data_updating.rs

Also implements some fixes for chordal decomp handling

cvxpy support hooks for #75

---

Cargo.toml

This updates `blas-src` and `lapack-src` to the latest versions, needed for the R package.

Update to latest blas and lapack src crates

---

python/clarabel/tests/test_json.py
src/julia/ClarabelRs/src/interface.jl
src/julia/ClarabelRs/src/types.jl
src/julia/types.rs
src/python/impl_default_py.rs
src/python/module_py.rs
src/qdldl/qdldl.rs
src/qdldl/test.rs
src/solver/core/kktsolvers/direct/quasidef/directldlkktsolver.rs
src/solver/core/kktsolvers/direct/quasidef/ldlsolvers/auto.rs
src/solver/core/kktsolvers/direct/quasidef/ldlsolvers/faer_ldl.rs
src/solver/core/kktsolvers/direct/quasidef/ldlsolvers/mod.rs
src/solver/core/kktsolvers/direct/quasidef/ldlsolvers/qdldl.rs
src/solver/core/kktsolvers/direct/quasidef/mod.rs
src/solver/core/kktsolvers/mod.rs
src/solver/implementations/default/info.rs
src/solver/implementations/default/info_print.rs
src/solver/implementations/default/kktsystem.rs
src/solver/implementations/default/settings.rs
src/solver/implementations/default/solver.rs
src/solver/mod.rs

When built with `faer-sparse`, choosing :auto as the ldlsolver type (now the default), will choose :qdldl when simplicial factorisation seems faster, and :faer if supernodal seems faster.
Implemented this way because qdldl is still a bit faster in the simplicial case.
Adds a `LinearSolverInfo` struct to the information output with some factorisation detail.

Adds "auto" option for ldlsolver selection

---

examples/rust/example_json.rs
src/algebra/csc/core.rs
src/python/impl_default_py.rs
src/solver/implementations/default/data_updating.rs
src/solver/implementations/default/ffi/settings.rs
src/solver/implementations/default/problemdata.rs
src/solver/implementations/default/settings.rs
tests/data_updating.rs

Add a setting to explicitly drop structural zeros on sparse problem inputs.
This setting defaults to `false` since dropping structural zeros disable problem data updates as a side effect.

structural dropzeros in P/A
